base_url = "https://blog.nyan.uz"
# theme = "zola.386"

# default_language = "en"
title = "Nyan Systems Blog"
description = "Bizning mikrosistemalarga sayohatimiz..."

highlight_code = true
compile_sass = true
generate_rss = true
build_search_index = true

taxonomies = [
  {name="categories", rss=true},
  {name="tags", rss=true},
]


[extra]
author = "Nyan Developers (LTC)"
year = "2024"
keywords = "nyan, nyancat, nya, compiler, developer"
theme_color = "#003366"
zola386_menu = [
  {path="", name="Asosiy"},
  {path="categories", name="Kategoriyalar"},
  {path="tags", name="Teglar"},
  {path="about", name="Biz haqimizda"},
]

### THIRD PARTY
# google_analytics = "UA-012345-67"
# disqus = "disqus-user"

### SOCIAL MEDIA
image = "https://raw.githubusercontent.com/lopes/zola.386/master/screenshot.png"
# twitter_user = "nyansystems"
# linkedin_user = "nyansystems"
github_user = "NyanSystems"
# gitlab_user = "NyanSystems"

### I18N WORDS
label_tags = "Teglar"
label_tag = "Teg"
label_categories = "Kategoriyalar"
label_category = "Kategoriya"
label_author = "Muallif"
label_date = "Sana"
label_taxonomy = "Taksonomiya"
label_reading = "O'qish vaqti"
label_read_more = "Ko'proq"
