base_url = "https://blog.nyan.uz"

# default_language = "en"
title = "Nyan Systems"
description = "Bizning mikrosistemalarga sayohatimiz..."

highlight_code = true
compile_sass = true
generate_rss = true
build_search_index = true

taxonomies = [
    { name = "categories", rss = true },
    { name = "tags", rss = true },
]

### EXTA CONFIGS
[extra]
main_url = "https://nyan.uz"
edit_url = "https://github.com/NyanSystems/purr/tree/main/content"
author = "Nyan Developers (LTC)"
year = "2024"
keywords = "nyan, nyancat, nya, compiler, developer"
theme_color = "#003366"
comments = true
zola386_menu = [
    { path = "", name = "Asosiy" },
    { path = "categories", name = "Kategoriyalar" },
    { path = "tags", name = "Teglar" },
    { path = "about", name = "Biz haqimizda" },
]

### SOCIAL MEDIA
image = "https://raw.githubusercontent.com/lopes/zola.386/master/screenshot.png"
telegram = "https://t.me/nyansystems"
# twitter_user = "nyansystems"
# linkedin_user = "nyansystems"
github_user = "NyanSystems"
# gitlab_user = "NyanSystems"

### I18N WORDS
label_tags = "Teglar"
label_tag = "Teg"
label_categories = "Kategoriyalar"
label_category = "Kategoriya"
label_author = "Muallif"
label_date = "Sana"
label_taxonomy = "Taksonomiya"
label_reading = "O'qish vaqti"
label_read_more = "Ko'proq"